sudo: required

env:
  global:
    - LIBRAW_GIT="git://github.com/LibRaw/LibRaw.git"
    - LIBRAW_CMAKE_GIT="git://github.com/LibRaw/LibRaw-cmake.git"

matrix:
  include:
    - services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
    
git:
  submodules: false

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io -e LIBRAW_GIT -e LIBRAW_CMAKE_GIT $DOCKER_IMAGE $PRE_CMD /io/travis/build.sh

after_success:
  - ls wheelhouse/
  - ls dist/
  - ls build/

# TODO use twine for sdist & wheels, and python setup.py upload_sphinx


