language: generic

matrix:
  include:
    - os: linux
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64

    - os: osx
      # use oldest available image to be as compatible as possible when producing wheels
      osx_image: xcode6.4 # = OS X 10.10
      # (NumPy 1.7.2 has no macOS wheels)
      env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.7.1

    - os: osx
      osx_image: xcode6.4
      env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.8.*

    - os: osx
      osx_image: xcode6.4
      env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.9.*

    - os: osx
      osx_image: xcode6.4
      env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.11.*

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/travis/build_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis/build_macos.sh; fi

after_success:
  - ls wheelhouse/
  - ls dist/
  - ls build/

before_deploy:
  - mv wheelhouse/rawpy*manylinux1*.whl dist/

deploy:
  provider: pypi
  user: letmaik
  skip_cleanup: true
  password:
    secure: "Gi+qCKpRNFjlvpOxBXjSNAq4yDhlSXfUUl9RZaOSdER+YURbc9/AMlfUuyOvpi09tAgwGnn9Hn3z7NqqjNV9auTcD30viMnevNbiyJaE2O/bw75FU9HqFmTM/OR7UVJp4sNtxtXy1Zp5CxmMnzRCjV3stQ9iaG9aJOV3sbUzDTQ="
  on:
    tags: true


